### ISSUE TITLE
Show all numbers

### ISSUE THREAD

**Issue by daniwaxman** [furkantektas/analog_clock#1]
Is it possible to show all hour numbers on the clock face?
showNumbers currently only shows 12/3/6/9

**Comment by furkantektas** [comment]
Since I need a minimal clock design, I didn't add beyond those numbers. So, it's not currently supported, but you can always send a PR for this feature 🙂

**Comment by furkantektas** [comment]
#4 makes that possible, thanks for the idea and @pidwid for the implementation.
