### ISSUE TITLE
The plugin `analog_clock` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by Sully55** [furkantektas/analog_clock#14]
The plugin `analog_clock` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by furkantektas** [comment]
Hi @Sully55 ,
I think this is fixed after merging #15 . I'm closing this issue, please feel free to re-open if it persists.
Thank you
