### ISSUE TITLE
Changing the displayed time is not working

### ISSUE THREAD

**Issue by JogyBlack** [furkantektas/analog_clock#16]
I have a static clock (isLive: false) that displays a time. Then, as a result of user action, it has to display a different time. 
This does not work. Instead of displaying the second time, the AnalogClock widget starts displaying the current system time.

Minimal example to demonstrate the problem:

```
import 'package:analog_clock/analog_clock.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  DateTime time = DateTime(2022, 1, 1, 12, 30, 0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: AnalogClock(
          isLive: false,
          datetime: time,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() => {
          time = time.add(const Duration(minutes: 15))
        }),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

When tapping the (+) button, the clock should show 12:45. Instead it shows the current time.

**Comment by JogyBlack** [comment]
Looking at the source of the AnalogClock widget, the bug is in didUpdateWidget:

```
    if (!widget.isLive && widget.datetime != oldWidget.datetime) {
      datetime = widget.datetime ?? DateTime.now();
      datetime = DateTime.now();
    }
```

The second assignment statement is wrong, as it unconditionally sets the clock time to the current time.

**Comment by SimonTellier** [comment]
` if (widget.isLive && widget.datetime != oldWidget.datetime) {
      datetime = DateTime.now();
    }`
(isLive: true)

**Comment by walles** [comment]
> The second assignment statement is wrong, as it unconditionally sets the clock time to the current time.

@JogyBlack did you consider making a PR?

**Comment by furkantektas** [comment]
Thank you @JogyBlack for spotting the bug and fixing it :) also for providing an example use case, @walles's PR (#18) fixed that bug. Thanks @walles for the PR!
