### ISSUE TITLE
pub.dev package links to timeline_list project instead of this one

### ISSUE THREAD

**Issue by maryx** [furkantektas/analog_clock#2]
1. Go to https://pub.dev/packages/analog_clock
2. Click on `Repository (Github)` and `View/report issues`. These two links go to https://github.com/furkantektas/timeline_list instead of this repo.

**Comment by furkantektas** [comment]
Thank you for pointing out. I was too lazy to write a completely new `pubspec.yaml` for this plugin. That's fixed now. 
Thanks.
