### ISSUE TITLE
Alignment of Clock numbers are not proper also position.

### ISSUE THREAD

**Issue by AVINASH21AK** [furkantektas/analog_clock#7]
i just had copy your example and run, i found alignment of Clock numbers are not proper also position.

![Screenshot 2020-05-12_15-59-13-749](https://user-images.githubusercontent.com/27337870/81673632-932e8d80-9469-11ea-93e3-73bd64fbe6bf.png)

**Comment by furkantektas** [comment]
Hi @AVINASH21AK ,
I am not sure if this is still valuable to you but I found out the reason. #4 introduced `showAllNumbers` option. Unfortunately this plugin does not have automated tests and I failed to spot the problem while accepting that PR. It's fixed now, thanks for pointing out the problem.
